generated
reduceTable
^#(
	#(18 1 #reduceActionForNumber1:) 
	#(19 1 #reduceActionForIdentifier1:) 
	#(20 1 #reduceActionForExpression_Statement2:) 
	#(15 1 #reduceActionForExpression_Statement2:) 
	#(16 1 #reduceActionForExpression_Statement2:) 
	#(17 1 #reduceActionForExpression_Statement2:) 
	#(17 1 #reduceActionForFactor2:) 
	#(23 2 #reduceActionForExpression_Statement2:) 
	#(14 3 #reduceActionForPrint1:) 
	#(17 3 #liftSecondValue:) 
	#(20 3 #reduceActionForExpression_Statement1:) 
	#(15 3 #reduceActionForExpression1:) 
	#(15 3 #reduceActionForExpression2:) 
	#(16 3 #reduceActionForTerm1:) 
	#(16 3 #reduceActionForTerm2:)
	).